### Amazon Advertisement  Data

In this project, the advertisement goal in Amazon website is set up using the data given by Amazon. 
The goal is to find the best terms that results in. more profits and sales and we need to distinguish the best and worst terms form this data frame. 

We have two products named **Quartz** and **JadeRoller** which we need to analyse seperately. 

The Primary goal is to find the best/worst terms and it can be developed to find other useful information from this raw data set. 

The data is obtained by thr Campaigns that seller sets on Amazon for advertisement. 

The Campaigns are divided to two parts:
- Automatic Campaigns
- Manual Camaigns

In Automatic Campaign Amazon finds the terms that customers search in their platform and list them in each row.
In Manual one, the seller finds his own favourite terms and ask Amazon to advertise for him.

**The necessary libararies are imoprted in the next cell. We also import our data from an excel file.**

In [258]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
%matplotlib inline

df = pd.read_excel('Business_data.xlsx')
df.head()

,Start Date,End Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Targeting,Match Type,Customer Search Term,Impressions,...,7 Day Total Sales,Total Advertising Cost of Sales (ACoS),Total Return on Advertising Spend (RoAS),7 Day Total Orders (#),7 Day Total Units (#),7 Day Conversion Rate,7 Day Advertised SKU Units (#),7 Day Other SKU Units (#),7 Day Advertised SKU Sales,7 Day Other SKU Sales
0,2021-01-06,2021-01-06,Not grouped,GBP,Quartz 3 Auto (16/12/2020),Quartz 3 Auto (16/12/2020),*,-,"""rose quartz roller""",1,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
1,2020-12-28,2020-12-28,Not grouped,GBP,Jade 3 Auto (16/12/2020),Jade 3 Auto (16/12/2020),*,-,100 jade roller,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
2,2020-12-26,2020-12-26,Not grouped,GBP,Jade 2 Auto (16/12/2020),Jade 2 Auto (16/12/2020),*,-,100% jade gua sha,1,...,10.82,0.137708,7.261745,1,1,1.0,1,0,10.82,0.0
3,2020-12-28,2020-12-28,Not grouped,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller,PHRASE,3d face roller,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
4,2021-01-02,2021-01-02,Not grouped,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller,PHRASE,amethyst face roller,68,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0

In [259]:
data = []
string = df['Campaign Name'].values
for st in string:
    y = "".join(itertools.takewhile(lambda x: x!=" ", st))
    if y == 'Manual':
       y = 'Jade'
    data.append(y)
df['Product_type'] = data

In [260]:
df_quartz = df[df['Product_type'] == 'Quartz' ]
df_jade = df[df['Product_type'] == 'Jade' ]

In [261]:
df['Product_type'] = df['Product_type'].map(lambda x: x.replace('jade','Jade'),na_action='ignore')
df['Product_type'] = df['Product_type'].map(lambda x: x.replace('quartz','Quartz'),na_action='ignore')

In [262]:
df['Product_type'].value_counts()

Jade      330
Quartz    205
Name: Product_type, dtype: int64

In [263]:
print("the number of rows and columns in the jade data are: " ,df_jade.shape)
print("the number of rows and columns in the quartz data are: " ,df_quartz.shape)

the number of rows and columns in the jade data are:  (289, 25)
the number of rows and columns in the quartz data are:  (182, 25)

**We have a data with 535 rows and 24 columns.**

Each of the rows represent the Campaign for advertisement. 
The columns are different features of each campaigns.

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 25 columns):
Start Date                                  535 non-null datetime64[ns]
End Date                                    535 non-null datetime64[ns]
Portfolio name                              535 non-null object
Currency                                    535 non-null object
Campaign Name                               535 non-null object
Ad Group Name                               535 non-null object
Targeting                                   535 non-null object
Match Type                                  535 non-null object
Customer Search Term                        535 non-null object
Impressions                                 535 non-null int64
Clicks                                      535 non-null int64
Click-Thru Rate (CTR)                       534 non-null float64
Cost Per Click (CPC)                        534 non-null float64
Spend                                       535 non-null float64
7 Day Total Sales                           535 non-null float64
Total Advertising Cost of Sales (ACoS)      84 non-null float64
Total Return on Advertising Spend (RoAS)    534 non-null float64
7 Day Total Orders (#)                      535 non-null int64
7 Day Total Units (#)                       535 non-null int64
7 Day Conversion Rate                       534 non-null float64
7 Day Advertised SKU Units (#)              535 non-null int64
7 Day Other SKU Units (#)                   535 non-null int64
7 Day Advertised SKU Sales                  535 non-null float64
7 Day Other SKU Sales                       535 non-null float64
Product_type                                535 non-null object
dtypes: datetime64[ns](2), float64(9), int64(6), object(8)
memory usage: 104.6+ KB

In [265]:
# The number of distinctive terms for advertisement 
df_jade['Customer Search Term'].value_counts()

face roller massager           5
face roller                    4
jade face roller               4
jade roller and gua sha set    4
face massager roller           3
                              ..
face scraper massager          1
jade roller and gua sha        1
sha set face roller            1
double face roller             1
b07nqlkb3g                     1
Name: Customer Search Term, Length: 214, dtype: int64

In [266]:
df_quartz['Customer Search Term'].value_counts()

gua sha               3
b07rfrgd5n            3
quartz face roller    3
b07z6bjnhq            3
b07f3whtp1            3
                     ..
jade gua sha tool     1
b087x8n5pv            1
jade roller face      1
b0895nq6ch            1
b07hsyssyb            1
Name: Customer Search Term, Length: 136, dtype: int64

In [267]:
# columns of the data
df.columns

Index(['Start Date', 'End Date', 'Portfolio name', 'Currency', 'Campaign Name',
       'Ad Group Name', 'Targeting', 'Match Type', 'Customer Search Term',
       'Impressions', 'Clicks', 'Click-Thru Rate (CTR)',
       'Cost Per Click (CPC)', 'Spend', '7 Day Total Sales',
       'Total Advertising Cost of Sales (ACoS) ',
       'Total Return on Advertising Spend (RoAS)', '7 Day Total Orders (#)',
       '7 Day Total Units (#)', '7 Day Conversion Rate',
       '7 Day Advertised SKU Units (#)', '7 Day Other SKU Units (#)',
       '7 Day Advertised SKU Sales', '7 Day Other SKU Sales', 'Product_type'],
      dtype='object')

In [268]:
# brief information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 25 columns):
Start Date                                  535 non-null datetime64[ns]
End Date                                    535 non-null datetime64[ns]
Portfolio name                              535 non-null object
Currency                                    535 non-null object
Campaign Name                               535 non-null object
Ad Group Name                               535 non-null object
Targeting                                   535 non-null object
Match Type                                  535 non-null object
Customer Search Term                        535 non-null object
Impressions                                 535 non-null int64
Clicks                                      535 non-null int64
Click-Thru Rate (CTR)                       534 non-null float64
Cost Per Click (CPC)                        534 non-null float64
Spend                                       535 non-null float64
7 Day Total Sales                           535 non-null float64
Total Advertising Cost of Sales (ACoS)      84 non-null float64
Total Return on Advertising Spend (RoAS)    534 non-null float64
7 Day Total Orders (#)                      535 non-null int64
7 Day Total Units (#)                       535 non-null int64
7 Day Conversion Rate                       534 non-null float64
7 Day Advertised SKU Units (#)              535 non-null int64
7 Day Other SKU Units (#)                   535 non-null int64
7 Day Advertised SKU Sales                  535 non-null float64
7 Day Other SKU Sales                       535 non-null float64
Product_type                                535 non-null object
dtypes: datetime64[ns](2), float64(9), int64(6), object(8)
memory usage: 104.6+ KB

In [269]:
def Terms_ACoS(df):
    
    """
    
    """
    
    df_new = pd.DataFrame()
    df_new['sum_of_the_spends'] = df.groupby('Customer Search Term')['Spend'].sum()
    df_new['sum_of_the_sales'] = df.groupby('Customer Search Term')['7 Day Total Sales'].sum()
    df_new = df_new[df_new.sum_of_the_sales != 0]
    df_new['ACOS_mean'] = df_new['sum_of_the_spends']/df_new['sum_of_the_sales']
    df_new = df_new.sort_values(ascending = True ,by = 'ACOS_mean')
    
    
    return df_new

## Accepted terms for JadeRoller

In [270]:
terms_df = Terms_ACoS(df_jade)

In [271]:
terms_df

                             sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
jade face roller ldreamam                 0.49             32.46   0.015096
guasha stone face scraper                 0.37             11.66   0.031732
crystal stone face roller                 0.40             11.66   0.034305
revolution face roller                    0.45             11.66   0.038593
beauty face roller                        0.57             11.66   0.048885
lapis face roller                         0.56             10.82   0.051756
jade face roller vibration                0.62             11.66   0.053173
jade face roller set                      2.10             34.14   0.061511
b08dg817wf                                1.04             11.66   0.089194
b08lv36nq4                                0.97             10.82   0.089649
b081w4d3rk                                1.10             10.82   0.101664
b07v5rm4tc                                1.14             10.82   0.105360
face roller and gua sha                   2.62             23.32   0.112350
face scraper                              2.49             21.64   0.115065
b08lvhykbb                                1.27             10.82   0.117375
b07cty1w1d                                1.37             11.66   0.117496
gua sha and jade roller                   1.41             10.82   0.130314
100% jade gua sha                         1.49             10.82   0.137708
jade rollers for face                     1.51             10.82   0.139556
face roller toner                         2.20             11.66   0.188679
marble face roller                        2.33             11.66   0.199828
b072c6jzqm                                2.27             10.82   0.209797
face roller jade                          2.56             11.66   0.219554
gua sha roller                            2.41             10.82   0.222736
anti wrinkle                              2.49             10.82   0.230129
b07rfrgd5n                                3.44             11.66   0.295026
face massager roller                      3.46             10.82   0.319778
gua sha jade                              3.91             11.66   0.335334
gua sha set                               4.36             10.82   0.402957
anti aging                                4.49             10.82   0.414972
face roller set                           4.79             10.82   0.442699
face roller massager                     21.14             44.96   0.470196
face massager                            10.93             21.64   0.505083
jade roller and gua sha set              16.77             32.46   0.516636
jade roller                              41.85             75.74   0.552548
jade stone face roller                    6.24             10.82   0.576710
face roller                             305.05            470.36   0.648546
rose quartz face roller                   7.11             10.82   0.657116
jade face roller                         59.31             87.40   0.678604
eye massager                              7.36             10.82   0.680222
gua sha                                  51.78             54.10   0.957116
skin care                                25.77             10.82   2.381701

In [272]:
accpeted_terms = terms_df[terms_df['ACOS_mean'] < 0.33].index

# Results:

In [273]:
for idx in accepted_terms:
    print(idx)

jade face roller ldreamam
guasha stone face scraper
crystal stone face roller
revolution face roller
beauty face roller
lapis face roller
jade face roller vibration
jade face roller set
stone face massager set
b08dg817wf
b08lv36nq4
b081w4d3rk
b07v5rm4tc
face roller and gua sha
face scraper
b08lvhykbb
b07cty1w1d
gua sha and jade roller
100% jade gua sha
jade rollers for face
face roller toner
marble face roller
face roller jade
gua sha roller
anti wrinkle
b07rfrgd5n

## Unaccepted terms for JadeRoller

In [274]:
unaccpeted_terms = terms_df[terms_df['ACOS_mean'] > 0.33].index

# Results:

In [275]:
for idx in un_accpeted_terms:
    print(idx)

gua sha jade
face massager roller
gua sha set
b072c6jzqm
face roller set
gua sha stone
face roller massager
anti aging
face massager
jade roller and gua sha set
face roller
rose quartz face roller
jade stone face roller
jade roller
jade face roller
eye massager
gua sha
skin care

## Accepted terms for Quartz

In [276]:
terms_df_q = Terms_ACoS(df_quartz)

In [277]:
terms_df_q

                           sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
b083qr4cpw                              0.64             16.58   0.038601
facial roller rose quartz               1.22             16.58   0.073583
b08cv8w4h9                              1.26             16.58   0.075995
rose roller                             1.30             15.82   0.082174
eye roller                              1.60             16.58   0.096502
face jade roller                        1.93             16.58   0.116405
b07pp7tnfs                              3.00             15.82   0.189633
rose face roller                        5.04             15.82   0.318584
b07phzs8mv                              5.34             15.82   0.337547
b07wzxwwpw                              6.14             16.58   0.370326
gua sha rose quartz                     7.06             15.82   0.446271
rose quartz face roller                17.94             32.40   0.553704
b088djsm22                             27.25             33.16   0.821773
gua sha                                31.44             16.58   1.896261
jade roller                           122.15             60.64   2.014347

In [278]:
accpeted_terms_q = terms_df_q[terms_df_q['ACOS_mean'] < 0.33].index

# Resluts:

In [279]:
for idx in accpeted_terms_q:
    print(idx)

b083qr4cpw
facial roller rose quartz
b08cv8w4h9
rose roller
eye roller
face jade roller
b07pp7tnfs
rose face roller

## Unaccepted terms for Quartz

In [280]:
unaccpeted_terms = terms_df_q[terms_df_q['ACOS_mean'] > 0.33].index

# Resluts:

In [281]:
for idx in accpeted_terms_q:
    print(idx)

b083qr4cpw
facial roller rose quartz
b08cv8w4h9
rose roller
eye roller
face jade roller
b07pp7tnfs
rose face roller