### Amazon Advertisement  Data

In this project, the advertisement goal in Amazon website is set up using the data given by Amazon. 
The goal is to find the best terms that results in. more profits and sales and we need to distinguish the best and worst terms form this data frame. 

We have two products named **Quartz** and **JadeRoller** which we need to analyse seperately. 

The Primary goal is to find the best/worst terms and it can be developed to find other useful information from this raw data set. 

The data is obtained by thr Campaigns that seller sets on Amazon for advertisement. 

The Campaigns are divided to two parts:
- Automatic Campaigns
- Manual Camaigns

In Automatic Campaign Amazon finds the terms that customers search in their platform and list them in each row.
In Manual one, the seller finds his own favourite terms and ask Amazon to advertise for him.

**The necessary libararies are imoprted in the next cell. We also import our data from an excel file.**

In [393]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
%matplotlib inline

df = pd.read_excel('Business_data.xlsx')
df.head()

,Start Date,End Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Targeting,Match Type,Customer Search Term,Impressions,...,7 Day Total Sales,Total Advertising Cost of Sales (ACoS),Total Return on Advertising Spend (RoAS),7 Day Total Orders (#),7 Day Total Units (#),7 Day Conversion Rate,7 Day Advertised SKU Units (#),7 Day Other SKU Units (#),7 Day Advertised SKU Sales,7 Day Other SKU Sales
0,2021-01-07,2021-01-07,jade,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller massager,PHRASE,electric face roller massager,5,...,0.00,NaN,0.000000,0,0,0.000000,0,0,0.00,0.0
1,2020-12-27,2021-01-01,jade,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller massager,PHRASE,face roller massager,584,...,11.66,0.236707,4.224638,1,1,0.166667,1,0,11.66,0.0
2,2021-01-01,2021-01-01,jade,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,jade roller and gua sha set,PHRASE,jade roller & gua sha set,14,...,0.00,NaN,0.000000,0,0,0.000000,0,0,0.00,0.0
3,2020-12-28,2021-01-08,jade,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,jade roller and gua sha set,PHRASE,jade roller and gua sha set,481,...,10.82,0.426987,2.341991,1,1,0.090909,1,0,10.82,0.0
4,2021-02-07,2021-02-07,jade,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,jade face roller,PHRASE,authentic jade face roller,2,...,11.66,0.036878,27.116279,1,1,1.000000,1,0,11.66,0.0

In [394]:
df.columns

Index(['Start Date', 'End Date', 'Portfolio name', 'Currency', 'Campaign Name',
       'Ad Group Name', 'Targeting', 'Match Type', 'Customer Search Term',
       'Impressions', 'Clicks', 'Click-Thru Rate (CTR)',
       'Cost Per Click (CPC)', 'Spend', '7 Day Total Sales',
       'Total Advertising Cost of Sales (ACoS) ',
       'Total Return on Advertising Spend (RoAS)', '7 Day Total Orders (#)',
       '7 Day Total Units (#)', '7 Day Conversion Rate',
       '7 Day Advertised SKU Units (#)', '7 Day Other SKU Units (#)',
       '7 Day Advertised SKU Sales', '7 Day Other SKU Sales'],
      dtype='object')

In [395]:
df['Total_sales'] = df['Spend']/df['Total Advertising Cost of Sales (ACoS) ']

In [396]:
df['Total_sales']= df['Total_sales'].fillna(0)

In [397]:
df['Total_sales']

0       0.00
1      11.66
2       0.00
3      10.82
4      11.66
       ...
726     0.00
727     0.00
728     0.00
729     0.00
730     0.00
Name: Total_sales, Length: 731, dtype: float64

In [398]:
df['Portfolio name'].value_counts()

jade      487
Quartz    244
Name: Portfolio name, dtype: int64

 First of all we need to clean the data to make it ready to work .

In [399]:
df['Portfolio name'].value_counts()

jade      487
Quartz    244
Name: Portfolio name, dtype: int64

In [400]:
# divide the data frame df to quartz and jade as below
df_quartz = df[df['Portfolio name'] == 'Quartz' ] # data associated with quartz product 
df_jade = df[df['Portfolio name'] == 'jade' ] # data associated with jade product

In [401]:
df_quartz.shape

(244, 25)

### We have now 2 data frame

1. Jade with 330 rows 
2. Quartz with 205 rows

In [402]:
print("the number of rows and columns in the jade data are: " ,df_jade.shape)
print("the number of rows and columns in the quartz data are: " ,df_quartz.shape)

the number of rows and columns in the jade data are:  (487, 25)
the number of rows and columns in the quartz data are:  (244, 25)


Each of the rows represent the Campaign for advertisement. 
The columns are different features of each campaigns.

**The whole data information is summarized in the next cell:**

In [403]:
# brief information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 25 columns):
Start Date                                  731 non-null datetime64[ns]
End Date                                    731 non-null datetime64[ns]
Portfolio name                              731 non-null object
Currency                                    731 non-null object
Campaign Name                               731 non-null object
Ad Group Name                               731 non-null object
Targeting                                   731 non-null object
Match Type                                  731 non-null object
Customer Search Term                        731 non-null object
Impressions                                 731 non-null int64
Clicks                                      731 non-null int64
Click-Thru Rate (CTR)                       730 non-null float64
Cost Per Click (CPC)                        730 non-null float64
Spend                                       731 non-null float64
7 Day Total Sales                           731 non-null float64
Total Advertising Cost of Sales (ACoS)      106 non-null float64
Total Return on Advertising Spend (RoAS)    730 non-null float64
7 Day Total Orders (#)                      731 non-null int64
7 Day Total Units (#)                       731 non-null int64
7 Day Conversion Rate                       730 non-null float64
7 Day Advertised SKU Units (#)              731 non-null int64
7 Day Other SKU Units (#)                   731 non-null int64
7 Day Advertised SKU Sales                  731 non-null float64
7 Day Other SKU Sales                       731 non-null float64
Total_sales                                 731 non-null float64
dtypes: datetime64[ns](2), float64(10), int64(6), object(7)
memory usage: 142.9+ KB

In [404]:
# The number of distinctive terms for advertisement of Jade Roller
df_jade['Customer Search Term'].value_counts()

gua sha                         7
jade roller                     7
face roller                     7
jade face roller                7
skin care                       7
                               ..
b07shg8lph                      1
jade face roller and gua sha    1
mo values face roller           1
jade roller 100% natural        1
face roller massager gold       1
Name: Customer Search Term, Length: 337, dtype: int64

In [405]:
# The number of distinctive terms for advertisement of Quartz
df_quartz['Customer Search Term'].value_counts()

face roller                6
rose quartz face roller    6
jade roller                6
gua sha                    5
b07n337qt6                 4
                          ..
rose gua sha               1
b01lz2uda0                 1
b08f23f38w                 1
facial massager gua sha    1
jade massager for face     1
Name: Customer Search Term, Length: 162, dtype: int64

### function to  find a new data frame based on the 3 important columns:

1. Customer Search Term
2. Spend
3. 7 Day Total Sales

we calculate sum of the sales and advertisement spends for each search terms which may be repeated in the data frame.

In [406]:

def Terms_ACoS(df):
    
    """
    INPUT:
    df - Pandas Data Frame 
    
    OUTPUT:
    df_new,df_sum_zero - The tuple for the new dataframe with two above mentioned columns and the the same dataframe with 
    zero sale. 
    
    """
    

    df_new = pd.DataFrame() # new data frame is defined
    df_new['sum_of_the_spends'] = df.groupby('Customer Search Term')['Spend'].sum() # sum of the all spends for each term is calculated 
    df_new['sum_of_the_sales'] = df.groupby('Customer Search Term')['Total_sales'].sum() # sum of the total sales for eac term is calculated
    
    df_sum_zero = df_new[df_new.sum_of_the_sales == 0] # sum of the sales which gives zero output are defined in the new data frame
    #df_new = df_new[df_new.sum_of_the_sales != 0]  # sum of the sales with non zero values are defined
    
    df_new['ACOS_mean'] = df_new['sum_of_the_spends']/df_new['sum_of_the_sales'] # new column is defined to calculate the ACOS(Total Advertising Cost of Sales)
    df_new = df_new.sort_values(ascending = True ,by = 'ACOS_mean') # we sort the values based on the column ACOS_mean in ascending order
    
    
    return df_new,df_sum_zero

## Accepted terms for JadeRoller

In [407]:
# the tuple of two data frames are defined using the function Terms_ACoS
terms_df,df_sum_zero = Terms_ACoS(df_jade)

In [408]:
terms_df

                             sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
quartz face roller full set               0.49             23.32   0.021012
crystal stone face roller                 0.40             11.66   0.034305
authentic jade face roller                0.43             11.66   0.036878
revolution face roller                    0.45             11.66   0.038593
jade and gua sha                          0.51             11.66   0.043739
...                                        ...               ...        ...
face roller herbivore                     0.63              0.00        inf
face roller gua sha                       1.01              0.00        inf
face roller for men                       0.59              0.00        inf
face roller depuff                        0.59              0.00        inf
yu ling jade face roller                  0.64              0.00        inf

[337 rows x 3 columns]

In [409]:
# # terms for zero values of the sales
df_sum_zero

                          sum_of_the_spends  sum_of_the_sales
Customer Search Term
100 jade roller                        1.47               0.0
100% jade gua sha tool                 0.69               0.0
3d face roller                         0.27               0.0
amatt face roller                      1.40               0.0
amethsyt face roller                   1.25               0.0
...                                     ...               ...
vibro face scraper                     0.18               0.0
white lotus jade gua sha               0.96               0.0
wing jade gua sha stone                0.50               0.0
womens face roller                     2.52               0.0
yu ling jade face roller               0.64               0.0

[278 rows x 2 columns]

In [410]:
# # terms for non-zero values of the ACOS_mean
np.isinf(terms_df["ACOS_mean"])

Customer Search Term
quartz face roller full set    False
crystal stone face roller      False
authentic jade face roller     False
revolution face roller         False
jade and gua sha               False
                               ...
face roller herbivore           True
face roller gua sha             True
face roller for men             True
face roller depuff              True
yu ling jade face roller        True
Name: ACOS_mean, Length: 337, dtype: bool

**Accepted terms are calculated based on the threshold 0.33**

In [411]:
# accepted terms are calculated based on the threshold 0.33
accepted_terms = terms_df[terms_df['ACOS_mean'] < 0.3].index

### Jade Roller 

# Results:

In [412]:
for idx in accepted_terms:
    print(idx)

quartz face roller full set
crystal stone face roller
authentic jade face roller
revolution face roller
jade and gua sha
jade face roller ldreamam
lapis face roller
jade face roller vibration
real jade gua sha massage tool
guasha stone face scraper
stone face massager set
face roller jade stone
face roller turata
real jade gua sha
jade gua sha tool
jade roller face roller
b081w4d3rk
face stone gua
gua sha jade roller
face roller and gua sha
b08lvhykbb
b07cty1w1d
b07z6bjnhq
face scraper
b08lv36nq4
face roller toner
100% jade gua sha
jade rollers for face
anti wrinkle
jade gua sha stone
gua sha and face roller
genuine jade face roller
b08dg817wf
jade face roller set
gua sha roller
gua sha and jade roller
b07rfrgd5n

## Unaccepted terms for JadeRoller

In [413]:
# we combine zero unacceptable results and unaccepteable threshold(0.33) result terms 
unaccpeted_terms = terms_df[terms_df['ACOS_mean'] > 0.3].index # unaccepted terms for threshold 0.33
unaccepted_zeros = df_sum_zero[df_sum_zero['sum_of_the_spends'] > 4 ].index # unaccepted zero values of the sales
unaccpeted_terms = unaccpeted_terms.union(unaccepted_zeros) # combine the two indexes

# Results:

In [414]:
for idx in unaccpeted_terms:
    print(idx)

100 jade roller
100% jade gua sha tool
3d face roller
amatt face roller
amethsyt face roller
amethyst face roller
amthesist face roller
anti aging
anti aging device
anti aging face roller and stone
anti aging mask
anti aging vitamins
anti wrinkle supplements
b001t9p2ng
b06xx56ndr
b071sfv6gx
b072c6jzqm
b075k72nrw
b075kfd928
b076611kcy
b079z4rzkx
b07f3trj9l
b07f3whtp1
b07g454sy7
b07h2qxp11
b07h2zttrw
b07h9547fm
b07k7fyw61
b07l3ybycg
b07m5spb7b
b07m7mj9fs
b07mjzbks6
b07nqlkb3g
b07nrcypnq
b07pf5bknq
b07pxq1dcb
b07qvf25mq
b07rkjc784
b07shg8lph
b07v5rm4tc
b07v8cz3c6
b07xhsr4tv
b07zp2y9ls
b07zx6kmrk
b0813q892z
b0816y23gd
b0818djgsb
b081jsq17f
b083m22gwh
b0853fcsng
b089k3drsq
b08bjd1129
b08cbryk7j
b08csc94bt
b08dl1px21
b08fj6nv7k
b08gbdvfhx
b08hmwf88s
b08n1mczq4
beauty care
beauty face roller
beauty roller face
beauty set
beauty sets
best face roller
best jade gua sha scraping massage tool
care face stone
ceramic face roller
circulation face roller
crystal face roller
crystal face roller jade
crystals face roller
danielle jade face roller
double face roller
electric face roller
electric face roller for circulation and t8ghten skin
electric face roller massager
emerald face roller
eye and face roller
eye massager
eye massager amazon
eye massager anti aging
eye roller
eye roller for puffy eyes
face beauty
face care
face care set
face jade roller
face jade stone
face massager
face massager anti wrinkle
face massager roller
face massager stone
face roller
face roller   gua sha
face roller amethyst
face roller and gua sha set
face roller and stone set
face roller automoness
face roller cheap
face roller crystal
face roller depuff
face roller eco
face roller for men
face roller gua sha
face roller herbivore
face roller ice
face roller jade
face roller jade rose
face roller kade
face roller kit
face roller massager
face roller massager and brush
face roller massager gold
face roller massager set
face roller microneedle
face roller oil
face roller pearl
face roller quartz
face roller revolution
face roller ridged
face roller rose quartz
face roller set
face roller spikes
face roller spots
face roller stone
face roller white
face rollers
face rollers for skincare
face rollers for women
face rollers for women jade
face scraper massager
face scraper quarts
face scraper stone
face scraper tool
face set
face stone massager
face stones
freeze face roller
frozen face roller
garnet face roller
gem face roller
gem stone face roller
gemstone face roller
genuine jade gua sha
gold face roller
green face roller
green jade gua sha
gua jade roller
gua sha
gua sha and jade roller set
gua sha and roller
gua sha and roller set
gua sha face massager
gua sha face roller
gua sha face scraper
gua sha jade
gua sha jade stone
gua sha massage tool
gua sha roller set
gua sha set
gua sha stone
gua sha stone and roller
gua sha stone jade
gua-sha
health stones
ice face roller
jade and gua sha pouch
jade eye roller
jade face
jade face massager roller
jade face roller
jade face roller and gua sha
jade face roller and gua sha set
jade face roller and gua sha tool
jade face roller cozymall
jade face roller emocci
jade face roller from uk
jade face roller gift
jade face roller gua sha massage set
jade face roller herbivore
jade face roller kit
jade face roller massager
jade face roller mens
jade face roller rose quartz
jade face roller sensitive skin
jade face roller set ce
jade face roller single
jade face roller uk
jade face rollers
jade face scraper
jade face set
jade face stone
jade gua sha
jade gua sha comb
jade gua sha massage tool
jade gua sha set
jade quartz face roller
jade roller
jade roller & gua sha set
jade roller 100% natural
jade roller and gua sha
jade roller and gua sha set
jade roller eyes
jade roller face
jade roller face gold
jade roller face massager
jade roller face music
jade roller for face
jade roller for face anti aging roller fav
jade roller gua
jade roller gua sha
jade roller jade face roller gua sha massager
jade roller set
jade skin roller face
jade stone
jade stone face roller
jade stone gua sha
jade stone roller
jade stone scraper
jasmine face roller
juggling face roller
korean face roller
lacura jade face roller
lymphatic face roller
marble face roller
massage face roller
massage roller
massage tool
massager for face and neck
massager neck
metal face roller
mineral face roller
mo values face roller
movalues face roller
natural gua sha
natural jade face roller
natural jade face roller and oil
natural jade gua sha and roller set
natural jade roller
natural jade roller for face
neck face roller
neck massager
neck massager roller
neck massager tool
neck roller
nephrite jade gua sha
nurse jamie face roller
obsidian face roller
original face roller
pink jade face roller
pocket jade gua sha stone
protected face roller
puffy eyes
quartz face roller
quartz jade face roller
real jade face roller
real jade gua sha stone
real jade roller for face
red face roller
rock face roller
roller and gua sha set
roller face
roller face massager
roller for face
roller for puffy eyes
roller massager
rose quartz face roller
rose quartz gua sha and roller
roselynboutique jade roller for face and gua sha set - beauty cosmetic facial skin roller massager tool - original handcraft natural green jade
rubber face roller
scraper face
sha set face roller
skin care
skin care face
skin care sets
skin massager
skin roller
skin roller for face
skin scraper
skin stone
skincare face roller
spa face roller
spikey face roller
stone face massager
stone face roller
stone face scraper
stone for face
stone roller
stone roller for face
the jade gua sha
the neck massager
tmj face scraper
topaz face roller
vibrating face roller
vibro face scraper
white lotus jade gua sha
wing jade gua sha stone
womens face roller
yu ling jade face roller

## Accepted terms for Quartz

In [415]:
terms_df_q,df_sum_zero_q = Terms_ACoS(df_quartz)

In [416]:
terms_df_q

                      sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
b083qr4cpw                         0.64             16.58   0.038601
b06xx56ndr                         1.14             16.58   0.068758
eye roller                         2.40             33.24   0.072202
b08cv8w4h9                         1.26             16.58   0.075995
rose roller                        4.46             32.48   0.137315
...                                 ...               ...        ...
b08gbdvfhx                         6.09              0.00        inf
b08hmwf88s                         1.02              0.00        inf
b08hqx1616                         0.99              0.00        inf
b08dmtrgrk                         1.31              0.00        inf
under eye roller                   0.60              0.00        inf

[162 rows x 3 columns]

In [417]:
# We  find the accepteable terms for threshold(0.33)   
accpeted_terms_q = terms_df_q[terms_df_q['ACOS_mean'] < 0.30].index # unaccepted terms for threshold 0.33

### Quartz 

#  Accepted Resluts:

In [418]:
for idx in accpeted_terms_q:
    print(idx)

b083qr4cpw
b06xx56ndr
eye roller
b08cv8w4h9
rose roller
face jade roller
b07pp7tnfs
facial roller rose quartz

## Unaccepted terms for Quartz

In [419]:
# We combine zero unacceptable results and unaccepteable threshold(0.33) result terms 
unaccpeted_terms_q = terms_df_q[terms_df_q['ACOS_mean'] > 0.30].index # unaccepted terms for threshold 0.33
unaccepted_zeros_q = df_sum_zero_q[df_sum_zero_q['sum_of_the_spends'] > 4 ].index # unaccepted zero values of the sales
unaccpeted_terms_q = unaccpeted_terms_q.union(unaccepted_zeros_q) # combine the two indexes

# Unaccepted Resluts:

In [420]:
for idx in unaccpeted_terms_q:
    print(idx)

"rose quartz roller"
authentic rose quartz
b01lz2uda0
b06xx3y43j
b072c6jzqm
b079z4rzkx
b07cslbfvc
b07f3trj9l
b07f3whtp1
b07h8m46ws
b07hsyssyb
b07jkn8911
b07l3ybycg
b07l4rpjb6
b07n337qt6
b07nqlkb3g
b07pf5bknq
b07phzs8mv
b07qb1ys7z
b07qvf25mq
b07rfrgd5n
b07rkjc784
b07sbdch6p
b07thv598l
b07v1mbddl
b07wzxwwpw
b07xhsr4tv
b07y44dcdb
b07yzbr293
b07z6bjnhq
b07zvp2kz5
b07zx6kmrk
b0818x422x
b0836msbyb
b084sxd866
b086172cm5
b087659jdv
b087ls64st
b087np2qfl
b087x8n5pv
b088djsm22
b0895nq6ch
b089fg7zvs
b089gmrczk
b08blhn73l
b08bzsjrjt
b08cbsyx8x
b08cvth6vm
b08dg817wf
b08dl27f53
b08dmtrgrk
b08dn7v61l
b08f23f38w
b08fbjbch8
b08g4zqqv6
b08gbdvfhx
b08hmwf88s
b08hqx1616
b08jd3q2d9
b08jshyxmy
b08l1wwlgq
b08lcnbbs6
b08lv36nq4
b08nyhsm85
beauty roller
beauty roller face
eye massager
eye massager roller
face beauty
face eye roller
face massager
face massager gua sha
face massager quartz
face massager roller
face roller
face roller & gua sha rose quartz
face roller massager
face roller quartz
face roller rose quartz
face roller rose quartz gua sha
facial massager
facial massager gua sha
facial massager roller
facial roller
facial roller massager
facial roller rose quartz revolution
facial rose quartz roller
facial skin roller
gua sha
gua sha face massager
gua sha face roller
gua sha jade
gua sha roller
gua sha rose
gua sha rose quartz
jade beauty roller
jade eye roller
jade face roller
jade face roller massager
jade gua rose
jade gua sha
jade gua sha tool
jade massager for face
jade roller
jade roller eyes
jade roller face
jade roller face massager
jade roller for face
jade roller gua sha
jade roller opnix
jade rollers for face
jade rose roller
massage stones
massage tools
natural jade roller
neck massager
neck roller
puffy eye roller
quartz eye roller
quartz face roller
quartz facial roller
quartz gua sha
quartz roller
quartz roller for face
roller and gua sha
roller face massager
roller face rose quartz
roller for face
roller massager face jade
rose and jade roller
rose face massager
rose face roller
rose face roller massager
rose gua sha
rose jade roller
rose massager
rose quartz
rose quartz face
rose quartz face massager
rose quartz face roller
rose quartz face roller 100%
rose quartz facial roller
rose quartz facial rollers
rose quartz gua sha
rose quartz jade roller
rose quartz roller
rose quartz roller facial
rose roller for face
rose roller quartz
skin roller for face
skin roller for face original quartz
skin roller rose quartz
steel eye roller
under eye roller