### Amazon Advertisement  Data

In this project, the advertisement goal in Amazon website is set up using the data given by Amazon. 
The goal is to find the best terms that results in. more profits and sales and we need to distinguish the best and worst terms form this data frame. 

We have two products named **Quartz** and **JadeRoller** which we need to analyse seperately. 

The Primary goal is to find the best/worst terms and it can be developed to find other useful information from this raw data set. 

The data is obtained by thr Campaigns that seller sets on Amazon for advertisement. 

The Campaigns are divided to two parts:
- Automatic Campaigns
- Manual Camaigns

In Automatic Campaign Amazon finds the terms that customers search in their platform and list them in each row.
In Manual one, the seller finds his own favourite terms and ask Amazon to advertise for him.

**The necessary libararies are imoprted in the next cell. We also import our data from an excel file.**

In [451]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
%matplotlib inline

df = pd.read_excel('Business_data.xlsx')
df.head()

,Start Date,End Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Targeting,Match Type,Customer Search Term,Impressions,...,7 Day Total Sales,Total Advertising Cost of Sales (ACoS),Total Return on Advertising Spend (RoAS),7 Day Total Orders (#),7 Day Total Units (#),7 Day Conversion Rate,7 Day Advertised SKU Units (#),7 Day Other SKU Units (#),7 Day Advertised SKU Sales,7 Day Other SKU Sales
0,2021-01-06,2021-01-06,Not grouped,GBP,Quartz 3 Auto (16/12/2020),Quartz 3 Auto (16/12/2020),*,-,"""rose quartz roller""",1,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
1,2020-12-28,2020-12-28,Not grouped,GBP,Jade 3 Auto (16/12/2020),Jade 3 Auto (16/12/2020),*,-,100 jade roller,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
2,2020-12-26,2020-12-26,Not grouped,GBP,Jade 2 Auto (16/12/2020),Jade 2 Auto (16/12/2020),*,-,100% jade gua sha,1,...,10.82,0.137708,7.261745,1,1,1.0,1,0,10.82,0.0
3,2020-12-28,2020-12-28,Not grouped,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller,PHRASE,3d face roller,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
4,2021-01-02,2021-01-02,Not grouped,GBP,Manual Jade 26/12/2020,Manual Jade 26/12/2020,face roller,PHRASE,amethyst face roller,68,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0

 First of all we need to clean the data to make it ready to work .

In [452]:
# Data is need to be divided to quartz and jade roller parts. 
data = [] # define a list 
string = df['Campaign Name'].values #  save Campaign names in the string object
for st in string:
    y = "".join(itertools.takewhile(lambda x: x!=" ", st)) # extract the terms jad and quartz from the asscociated columns
    if y == 'Manual':
        y = 'Jade'
    data.append(y) # append each of the keywords to the list data
df['Product_type'] = data # add a new column product_type to the dataframe df

In [453]:
# some of the terms are not in capital so we replace them with capital ones. 
df['Product_type'] = df['Product_type'].map(lambda x: x.replace('jade','Jade'),na_action='ignore')
df['Product_type'] = df['Product_type'].map(lambda x: x.replace('quartz','Quartz'),na_action='ignore')

In [454]:
# divide the data frame df to quartz and jade as below
df_quartz = df[df['Product_type'] == 'Quartz' ] # data associated with quartz product 
df_jade = df[df['Product_type'] == 'Jade' ] # data associated with jade product

### We have now 2 data frame

1. Jade with 330 rows 
2. Quartz with 205 rows

In [455]:
df['Product_type'].value_counts()

Jade      330
Quartz    205
Name: Product_type, dtype: int64

In [456]:
print("the number of rows and columns in the jade data are: " ,df_jade.shape)
print("the number of rows and columns in the quartz data are: " ,df_quartz.shape)

the number of rows and columns in the jade data are:  (330, 25)
the number of rows and columns in the quartz data are:  (205, 25)


Each of the rows represent the Campaign for advertisement. 
The columns are different features of each campaigns.

**The whole data information is summarized in the next cell:**

In [457]:
# brief information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 25 columns):
Start Date                                  535 non-null datetime64[ns]
End Date                                    535 non-null datetime64[ns]
Portfolio name                              535 non-null object
Currency                                    535 non-null object
Campaign Name                               535 non-null object
Ad Group Name                               535 non-null object
Targeting                                   535 non-null object
Match Type                                  535 non-null object
Customer Search Term                        535 non-null object
Impressions                                 535 non-null int64
Clicks                                      535 non-null int64
Click-Thru Rate (CTR)                       534 non-null float64
Cost Per Click (CPC)                        534 non-null float64
Spend                                       535 non-null float64
7 Day Total Sales                           535 non-null float64
Total Advertising Cost of Sales (ACoS)      84 non-null float64
Total Return on Advertising Spend (RoAS)    534 non-null float64
7 Day Total Orders (#)                      535 non-null int64
7 Day Total Units (#)                       535 non-null int64
7 Day Conversion Rate                       534 non-null float64
7 Day Advertised SKU Units (#)              535 non-null int64
7 Day Other SKU Units (#)                   535 non-null int64
7 Day Advertised SKU Sales                  535 non-null float64
7 Day Other SKU Sales                       535 non-null float64
Product_type                                535 non-null object
dtypes: datetime64[ns](2), float64(9), int64(6), object(8)
memory usage: 104.6+ KB

In [458]:
# The number of distinctive terms for advertisement of Jade Roller
df_jade['Customer Search Term'].value_counts()

jade face roller             7
face roller                  7
jade roller                  6
face roller massager         6
skin care                    6
                            ..
roller for puffy eyes        1
b07h2zttrw                   1
crystal stone face roller    1
gua sha and face roller      1
b07nqlkb3g                   1
Name: Customer Search Term, Length: 223, dtype: int64

In [459]:
# The number of distinctive terms for advertisement of Quartz
df_quartz['Customer Search Term'].value_counts()

face roller                  6
rose quartz face roller      6
jade roller                  6
gua sha                      5
b07f3whtp1                   4
                            ..
facial roller rose quartz    1
facial skin roller           1
skin roller for face         1
jade gua sha tool            1
b07hsyssyb                   1
Name: Customer Search Term, Length: 140, dtype: int64

### function to  find a new data frame based on the 3 important columns:

1. Customer Search Term
2. Spend
3. 7 Day Total Sales

we calculate sum of the sales and advertisement spends for each search terms which may be repeated in the data frame.

In [460]:

def Terms_ACoS(df):
    
    """
    INPUT:
    df - Pandas Data Frame 
    
    OUTPUT:
    df_new,df_sum_zero - The tuple for the new dataframe with two above mentioned columns and the the same dataframe with 
    zero sale. 
    
    """
    
    df_new = pd.DataFrame() # new data frame is defined
    df_new['sum_of_the_spends'] = df.groupby('Customer Search Term')['Spend'].sum() # sum of the all spends for each term is calculated 
    df_new['sum_of_the_sales'] = df.groupby('Customer Search Term')['7 Day Total Sales'].sum() # sum of the spends for each. term is calculated
    
    df_sum_zero = df_new[df_new.sum_of_the_sales == 0] # sum of the sales which gives zero output are defined in the new data frame
    df_new = df_new[df_new.sum_of_the_sales != 0]  # sum of the sales with non zero values are defined
    
    df_new['ACOS_mean'] = df_new['sum_of_the_spends']/df_new['sum_of_the_sales'] # new column is defined to calculate the ACOS(Total Advertising Cost of Sales)
    df_new = df_new.sort_values(ascending = True ,by = 'ACOS_mean') # we sort the values based on the column ACOS_mean in ascending order
    
    
    return df_new,df_sum_zero

## Accepted terms for JadeRoller

In [461]:
# the tuple of two data frames are defined using the function Terms_ACoS
terms_df,df_sum_zero = Terms_ACoS(df_jade)

In [462]:
# # terms for zero values of the sales
df_sum_zero

                          sum_of_the_spends  sum_of_the_sales
Customer Search Term
100 jade roller                        1.47               0.0
3d face roller                         0.27               0.0
amethyst face roller                   0.51               0.0
anti aging device                      0.52               0.0
anti aging mask                        0.63               0.0
...                                     ...               ...
the neck massager                      1.37               0.0
topaz face roller                      0.60               0.0
vibro face scraper                     0.18               0.0
womens face roller                     2.52               0.0
yu ling jade face roller               0.64               0.0

[179 rows x 2 columns]

In [463]:
# # terms for non-zero values of the ACOS_mean
terms_df

                             sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
jade face roller ldreamam                 0.49             32.46   0.015096
guasha stone face scraper                 0.37             11.66   0.031732
crystal stone face roller                 0.40             11.66   0.034305
revolution face roller                    0.45             11.66   0.038593
beauty face roller                        0.57             11.66   0.048885
lapis face roller                         0.56             10.82   0.051756
jade face roller vibration                0.62             11.66   0.053173
jade face roller set                      2.10             34.14   0.061511
stone face massager set                   0.76             10.82   0.070240
b08dg817wf                                1.04             11.66   0.089194
b08lv36nq4                                0.97             10.82   0.089649
b081w4d3rk                                1.10             10.82   0.101664
b07v5rm4tc                                1.14             10.82   0.105360
face roller and gua sha                   2.62             23.32   0.112350
face scraper                              2.49             21.64   0.115065
b08lvhykbb                                1.27             10.82   0.117375
b07cty1w1d                                1.37             11.66   0.117496
gua sha and jade roller                   1.41             10.82   0.130314
100% jade gua sha                         1.49             10.82   0.137708
jade rollers for face                     1.51             10.82   0.139556
face roller toner                         2.20             11.66   0.188679
marble face roller                        2.33             11.66   0.199828
face roller jade                          2.56             11.66   0.219554
gua sha roller                            2.41             10.82   0.222736
anti wrinkle                              2.49             10.82   0.230129
b07rfrgd5n                                3.44             11.66   0.295026
gua sha jade                              3.91             11.66   0.335334
face massager roller                      3.96             10.82   0.365989
gua sha set                               4.36             10.82   0.402957
b072c6jzqm                                4.57             10.82   0.422366
face roller set                           4.79             10.82   0.442699
gua sha stone                             4.95             10.82   0.457486
face roller massager                     21.97             44.96   0.488657
anti aging                                5.99             10.82   0.553604
face massager                            12.40             21.64   0.573013
jade roller and gua sha set              18.78             32.46   0.578558
face roller                             321.76            492.00   0.653984
rose quartz face roller                   7.11             10.82   0.657116
jade stone face roller                    7.12             10.82   0.658041
jade roller                              53.12             75.74   0.701347
jade face roller                         62.57             87.40   0.715904
eye massager                              8.84             10.82   0.817006
gua sha                                  62.86             54.10   1.161922
skin care                                41.01             21.64   1.895102

**Accepted terms are calculated based on the threshold 0.33**

In [464]:
# accepted terms are calculated based on the threshold 0.33
accpeted_terms = terms_df[terms_df['ACOS_mean'] < 0.33].index

### Jade Roller 

# Results:

In [465]:
for idx in accepted_terms:
    print(idx)

jade face roller ldreamam
guasha stone face scraper
crystal stone face roller
revolution face roller
beauty face roller
lapis face roller
jade face roller vibration
jade face roller set
stone face massager set
b08dg817wf
b08lv36nq4
b081w4d3rk
b07v5rm4tc
face roller and gua sha
face scraper
b08lvhykbb
b07cty1w1d
gua sha and jade roller
100% jade gua sha
jade rollers for face
face roller toner
marble face roller
face roller jade
gua sha roller
anti wrinkle
b07rfrgd5n

## Unaccepted terms for JadeRoller

In [466]:
# we combine zero unacceptable results and unaccepteable threshold(0.33) result terms 
unaccpeted_terms = terms_df[terms_df['ACOS_mean'] > 0.33].index # unaccepted terms for threshold 0.33
unaccepted_zeros = df_sum_zero[df_sum_zero['sum_of_the_spends'] > 4 ].index # unaccepted zero values of the sales
unaccpeted_terms = unaccpeted_terms.union(unaccepted_zeros) # combine the two indexes

# Results:

In [467]:
for idx in unaccpeted_terms:
    print(idx)

anti aging
b072c6jzqm
b07g454sy7
b07m5spb7b
b07qvf25mq
beauty set
eye massager
face care
face massager
face massager roller
face roller
face roller massager
face roller set
gua sha
gua sha jade
gua sha set
gua sha stone
jade face roller
jade roller
jade roller and gua sha set
jade roller face
jade stone face roller
jade stone gua sha
neck massager
roller face massager
rose quartz face roller
skin care
skin care sets
skin roller
stone face roller

## Accepted terms for Quartz

In [468]:
terms_df_q,df_sum_zero_q = Terms_ACoS(df_quartz)

In [469]:
terms_df_q

                           sum_of_the_spends  sum_of_the_sales  ACOS_mean
Customer Search Term
b083qr4cpw                              0.64             16.58   0.038601
b06xx56ndr                              1.14             16.58   0.068758
facial roller rose quartz               1.22             16.58   0.073583
b08cv8w4h9                              1.26             16.58   0.075995
rose roller                             1.30             15.82   0.082174
eye roller                              1.60             16.58   0.096502
face jade roller                        1.93             16.58   0.116405
b07pp7tnfs                              3.00             15.82   0.189633
rose face roller                        5.04             15.82   0.318584
b07phzs8mv                              5.34             15.82   0.337547
b07wzxwwpw                              6.14             16.58   0.370326
gua sha rose quartz                     7.06             15.82   0.446271
b088djsm22                             27.99             49.74   0.562726
rose quartz face roller                20.49             32.40   0.632407
gua sha                                36.00             33.16   1.085645
jade roller                           127.87             60.64   2.108674

In [470]:
# We  find the accepteable terms for threshold(0.33)   
accpeted_terms_q = terms_df_q[terms_df_q['ACOS_mean'] < 0.33].index # unaccepted terms for threshold 0.33

### Quartz 

#  Accepted Resluts:

In [471]:
for idx in accpeted_terms_q:
    print(idx)

b083qr4cpw
b06xx56ndr
facial roller rose quartz
b08cv8w4h9
rose roller
eye roller
face jade roller
b07pp7tnfs
rose face roller

## Unaccepted terms for Quartz

In [472]:
# We combine zero unacceptable results and unaccepteable threshold(0.33) result terms 
unaccpeted_terms_q = terms_df_q[terms_df_q['ACOS_mean'] > 0.33].index # unaccepted terms for threshold 0.33
unaccepted_zeros_q = df_sum_zero_q[df_sum_zero_q['sum_of_the_spends'] > 4 ].index # unaccepted zero values of the sales
unaccpeted_terms_q = unaccpeted_terms_q.union(unaccepted_zeros_q) # combine the two indexes

# Unaccepted Resluts:

In [473]:
for idx in unaccpeted_terms_q:
    print(idx)

b079z4rzkx
b07f3whtp1
b07pf5bknq
b07phzs8mv
b07rfrgd5n
b07wzxwwpw
b07z6bjnhq
b088djsm22
b08dg817wf
b08gbdvfhx
face roller
gua sha
gua sha rose quartz
jade face roller
jade roller
quartz face roller
rose quartz face roller
rose quartz roller facial